// Table of Contents data for Arban's Complete Method.
// Negative page numbers are preface pages (displayed as Roman numerals).
// Shared by the sidebar tree (TableOfContents) and search (utils/tocSearch).

export interface Section {
  title: string;
  page: number;
  subsections?: Section[];
}

export const sections: Section[] = [
  {
    title: "Title Page and Introduction",
    page: -7,
    subsections: [
      { title: "Cover", page: -7 },
      { title: "Musical Terms", page: -6 },
      { title: "Report", page: -5 },
      { title: "Arban Biography", page: -4 },
      { title: "Preface", page: -3 },
      { title: "Table of Harmonics", page: -1 },
      { title: "Diagram of Cornet", page: 0 },
      { title: "Compass of Cornet", page: 1 },
      { title: "Position of Mouthpiece on the Lips", page: 3 },
      { title: "Style", page: 6 },
    ],
  },
  {
    title: "First Studies",
    page: 11,
    subsections: [
      {
        title: "First Studies",
        page: 11,
        subsections: [
          { title: "#1 --> #6", page: 11 },
          { title: "#7 -->#9", page: 12 },
        ],
      },
      { title: "The Study of Syncopation", page: 23 },
      { title: "Studies on Dotted Eighth Notes", page: 26 },
      { title: "Studies of the Slur, Explanation", page: 37 },
      { title: "Studies of the Slur", page: 39 },
      { title: "Lip Trills", page: 44 },
    ],
  },
  {
    title: "Scale Studies",
    page: 57,
    subsections: [
      { title: "Major Scales", page: 59 },
      { title: "Minor Scales", page: 75 },
      { title: "Chromatic Scales", page: 76 },
      { title: "Chromatic Triples", page: 80 },
    ],
  },
  {
    title: "Grace Notes",
    page: 87,
    subsections: [
      { title: "Preparatory Exercises on the Gruppetto", page: 91 },
      { title: "The Gruppetto", page: 99 },
      { title: "The Double Appoggiatura", page: 104 },
      { title: "The Simple Appoggiatura", page: 106 },
      { title: "The Portamento", page: 110 },
      { title: "The Trill or Shake", page: 111 },
      { title: "The Mordant", page: 120 },
    ],
  },
  {
    title: "More Advanced Studies",
    page: 123,
    subsections: [
      { title: "Studies on the Intervals", page: 125 },
      { title: "Octaves and Tenths", page: 131 },
      { title: "Exercises on Triplets", page: 132 },
      { title: "Exercises on Sixteenth Notes", page: 137 },
      { title: "Major and Minor Chords", page: 142 },
      { title: "The Chord of the Dominant Seventh", page: 147 },
      { title: "The Chord of the Diminished Seventh", page: 149 },
      { title: "Cadenzas", page: 152 },
    ],
  },
  {
    title: "Tonguing",
    page: 153,
    subsections: [
      { title: "Triple Tonguing", page: 155 },
      { title: "Double Tonguing", page: 175 },
      { title: "The Slur and Double Tonguing", page: 183 },
      { title: "Tonguing as Applied to the Trumpet", page: 188 },
    ],
  },
  {
    title: "The Art of Phrasing",
    page: 191,
    subsections: [
      {
        title: "150 Classic and Popular Melodies",
        page: 191,
        // Titles extracted from the page scans via OCR (scripts/pdf-extract.py +
        // scripts/extract-exercise-titles.mjs); illegible ones are omitted
        subsections: [
          { title: "Robin Adair", page: 191 },
          { title: "Loving, I Think of Thee", page: 191 },
          { title: "My Pretty Jane", page: 191 },
          { title: "How Fair Thou Art", page: 192 },
          { title: "God Save the Queen", page: 192 },
          { title: "Last Rose of Summer", page: 192 },
          { title: "My Own, My Guiding Star", page: 192 },
          { title: "Why Do I Weep for Thee?", page: 193 },
          { title: "Blue Bells of Scotland", page: 193 },
          { title: "Dutch Air", page: 193 },
          { title: "Now the Swallows Are Returning", page: 193 },
          { title: "Who Shall Be Fairest?", page: 194 },
          { title: "Russian Hymn", page: 194 },
          { title: "Ye Tears", page: 194 },
          { title: "Puritan's Daughter", page: 194 },
          { title: "Woodman, Spare That Tree", page: 195 },
          { title: "Love Not", page: 195 },
          { title: "Wert Thou But Mine Own Love", page: 195 },
          { title: "We May Be Happy Yet", page: 196 },
          { title: "Constance", page: 196 },
          { title: "The Heart of Thy Nora Is Breaking for Thee", page: 196 },
          { title: "The Heart Bowed Down", page: 197 },
          { title: "German Song", page: 197 },
          { title: "Friends of My Youth", page: 197 },
          { title: "Romance", page: 198 },
          { title: "My Bark Which O'er the Tide", page: 199 },
          { title: "'Twas Rank and Fame", page: 199 },
          { title: "Vien, Leonora", page: 199 },
          { title: "Sicilian Vespers", page: 200 },
          { title: "Black Eyed Susan", page: 200 },
          { title: "Good-Bye, Sweetheart", page: 200 },
          { title: "Farewell to Thee, Mary", page: 201 },
          { title: "In Happy Moments", page: 201 },
          { title: "Call Me Thine Own", page: 201 },
          { title: "Kathleen Mavourneen", page: 201 },
          { title: "Love's Own Tear", page: 202 },
          { title: "Restore Those Visions Bright", page: 203 },
          { title: "Be Still", page: 204 },
          { title: "La Gazza Ladra", page: 207 },
          { title: "La Donna del Lago", page: 207 },
          { title: "La Cenerentola", page: 208 },
          { title: "Alla Vita Che T'Arride", page: 208 },
          { title: "The Irish Emigrant", page: 209 },
          { title: "Don Juan", page: 209 },
          { title: "Can I Be Dreaming?", page: 209 },
          { title: "Le Desir", page: 210 },
          { title: "Andante from A Major Symphony", page: 210 },
          { title: "Al Ben de' Tuoi Qual Vittima", page: 210 },
          { title: "Funeral March", page: 211 },
          { title: "Ariette", page: 212 },
          { title: "Song of the Mermaids", page: 212 },
          { title: "Romeo", page: 213 },
          { title: "Serenade", page: 215 },
          { title: "Lancashire Clog Dance", page: 216 },
          { title: "Il Trovatore", page: 219 },
          { title: "Il Trovatore", page: 221 },
          { title: "Le Porte Etendard", page: 222 },
          { title: "The Tear", page: 222 },
          { title: "Melody", page: 223 },
          { title: "La Parisina", page: 223 },
          { title: "Daughter of the Regiment", page: 224 },
          { title: "Capuletti", page: 225 },
          { title: "Dopo Due Lustri", page: 225 },
          { title: "Il Crociato", page: 225 },
          { title: "Absence", page: 226 },
          { title: "Semiramide", page: 227 },
          { title: "L'Elisire d'Amore", page: 227 },
          { title: "Il Trovatore", page: 228 },
          { title: "The Magic Flute", page: 228 },
          { title: "Austrian Hymn", page: 230 },
          { title: "La Somnambule", page: 231 },
          { title: "In Mia Man Alfin Tu Sei", page: 233 },
          { title: "Il Rival Salvar Tu Dei", page: 233 },
          { title: "Thou Art So Near, and Yet So Far", page: 234 },
          { title: "Ernani", page: 237 },
          { title: "Home Sweet Home", page: 240 },
          { title: "Blue Bells of Scotland (variations)", page: 242 },
          { title: "Yankee Doodle", page: 243 },
          { title: "God Save the Queen (variations)", page: 244 },
        ],
      },
      {
        title: "68 Duets",
        page: 246,
        subsections: [
          { title: "Russian Hymn", page: 246 },
          { title: "Cradle Song", page: 246 },
          { title: "Adeste Fideles", page: 248 },
          { title: "God Save the Queen", page: 248 },
          { title: "Air by Gretry", page: 249 },
          { title: "Noel Ancien", page: 249 },
          { title: "Air by Beethoven", page: 250 },
          { title: "Arabian Song", page: 250 },
          { title: "Serenade", page: 251 },
          { title: "La Romanesca", page: 251 },
          { title: "Romance from 'Joseph'", page: 251 },
          { title: "Song of Master Adam", page: 254 },
          { title: "Le Souvenir", page: 254 },
          { title: "The Two Savoyards", page: 255 },
          { title: "Silent Sorrow", page: 255 },
          { title: "L'Elisire d'Amore", page: 257 },
          { title: "Prayer to the Virgin", page: 258 },
          { title: "Spanish Royal March", page: 258 },
          { title: "March of Two Misers", page: 259 },
          { title: "Melody", page: 259 },
          { title: "Country Wedding", page: 260 },
          { title: "Bivouac Song", page: 260 },
          { title: "Birthday Festival", page: 261 },
          { title: "German Song", page: 261 },
          { title: "Bolero", page: 264 },
          { title: "Norma", page: 265 },
          { title: "Melody", page: 265 },
          { title: "Last Rose of Summer", page: 266 },
          { title: "French Air", page: 268 },
          { title: "Air from 'Somnambula'", page: 270 },
          { title: "Wind and Wave", page: 270 },
          { title: "Italian Air", page: 271 },
          { title: "Alpine Horn", page: 272 },
          { title: "The Hermit", page: 272 },
          { title: "Waltz from 'Puritani'", page: 275 },
          { title: "Siege of Rochelle", page: 277 },
          { title: "Hail! Star of Mary", page: 278 },
          { title: "The Two Friends", page: 279 },
          { title: "The Fox Hunters", page: 281 },
        ],
      },
    ],
  },
  {
    title: "Characteristic Studies",
    page: 285,
    subsections: [
      { title: "#1", page: 285 },
      { title: "#2", page: 286 },
      { title: "#3", page: 287 },
      { title: "#4", page: 288 },
      { title: "#5", page: 289 },
      { title: "#6", page: 290 },
      { title: "#7", page: 291 },
      { title: "#8", page: 292 },
      { title: "#9", page: 293 },
      { title: "#10", page: 294 },
      { title: "#11", page: 295 },
      { title: "#12", page: 296 },
      { title: "#13", page: 297 },
      { title: "#14", page: 298 },
    ],
  },
  {
    title: "Celebrated Fantaisies and Airs Variés",
    page: 300,
    subsections: [
      { title: "Fantasie and Variations on a Cavatina", page: 301 },
      { title: "Fantasie and Variations on Acteon", page: 305 },
      { title: "Fantasie Brilliante", page: 309 },
      { title: "Variations on a Tyrolean Song", page: 313 },
      { title: "Variations on a song 'The Beautiful Snow'", page: 317 },
      { title: "Cavatina and Variations", page: 320 },
      { title: "Air Varie on a Folk Song 'The Little Swiss Boy'", page: 323 },
      { title: "Fantasie and Variations on a German Theme", page: 331 },
      { title: "Variations on a favorite theme by C.M. von Weber", page: 335 },
      { title: "Fantasie and Variations on the Carnival of Venice", page: 339 },
      { title: "Variations on a theme from Norma by V. Bellini", page: 344 },
    ],
  },
];
